name: Csharp Deploy To Lambda $(Date:yyyyMMdd) $(Rev:r)

trigger:
- dev

pool: 
 vmImage: windows-latest

steps:
- task: UseDotNet@2
  displayName: 'Installing .Net6'
  inputs:
    version: '6.x'

- task: LambdaNETCoreDeploy@1
  inputs:
    awsCredentials: 'AWS-GP-Csharp-Deploy'
    regionName: 'ap-south-1'
    command: 'deployFunction'
    packageOnly: false
    functionName: 'DemoCsharpDeploy'
    localZipFile: '$(Build.ArtifactStagingDirectory)/Csharp-New-Zip/'
 