name: Csharp Deploy To Lambda $(Date:yyyyMMdd) $(Rev:r)

trigger:
- dev

pool: 
 vmImage: windows-latest

steps:
- task: UseDotNet@2
  displayName: 'Installing .Net6'
  inputs:
    version: '6.x'
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
   command: 'build'
- task: DotNetCoreCLI@2
  displayName: 'Unit Test'
  inputs:
    command: 'test'
- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
    versioningScheme: 'on'
- task: PublishBuildArtifacts@1
  displayName: 'push to pipeline'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Csharp-New-Zip'
    publishLocation: 'Container'
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'Csharp-New-Zip'
    downloadPath: '$(System.ArtifactsDirectory)'
- task: AmazonWebServices.aws-vsts-tools.LambdaDeployFunction.LambdaDeployFunction@1
  displayName: 'Deploy Lambda Function: DemoCsharpDeploy'
  inputs:
    awsCredentials: 'AWS-GP-Csharp-Deploy'
    regionName: 'ap-south-1'
    functionName: DemoCsharpDeploy
    codeLocation: 'localfile'
    localZipFile: '$(Build.ArtifactStagingDirectory)/Csharp-New-Zip/New-CS.zip'
#    localZipFile: 'New-CS/bin/Debug/net6.0/New-CS.dll'
# - task: LambdaDeployFunction@1
#   displayName: 'Deploy Lambda Function'
#   inputs:
#     awsCredentials: 'AWS-GP-Csharp-Deploy'
#     regionName: 'ap-south-1'
#     deploymentMode: 'codeandconfiguration'
#     functionName: 'DemoCsharpDeploy'
#     description: 'From AzureDevops'
# #    functionHandler: 'awsLambdaCICDPipeline::awsLambdaCICDPipeline.Function::FunctionHandler'
# #    runtime: 'dotnetcore2.1'
#     codeLocation: 'localfile'
#     localZipFile: '$(Build.ArtifactStagingDirectory)/drop/awsLambdaCICDPipeline.zip'
#     roleARN: '$(AWS-Lambda-ARN)'
# - task: LambdaNETCoreDeploy@1
#   inputs:
#     awsCredentials: 'AWS-GP-Csharp-Deploy'
#     regionName: 'ap-south-1'
#     command: 'deployFunction'
#     packageOnly: false
#     functionName: 'DemoCsharpDeploy'
#     localZipFile: '$(System.ArtifactsDirectory)/Csharp-New-Zip/'
 