name: C Sharp Dev Build and Package pipeline

variables:
  dir: 'cd root-path/main'
  file: 'csharp.zip'

trigger: 
-  env1
-  env2

stages:
- stage: Build and Test
  jobs:
    - job: Set up Runtime
      pool: 
      steps:
        -  task:

        -  task:

        -  script: ./a.out
    
    - job: Check
      pool: 
      steps:
      -  script: ls

- stage: Deploy
  jobs:
  - job: Deploy to Lambda
    steps:
      - task: LambdaNETCoreDeploy@1
        inputs:
          awsCredentials: 'AWS-GP-Csharp-Deploy'
          regionName: 'ap-south-1'
          command: 'deployFunction'
          packageOnly: false
          functionName: 'DemoCsharpDeploy'
          codeLocation:

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
   command: 'build'
- task: DotNetCoreCLI@2
  displayName: 'Unit Test'
  inputs:
    command: 'test'
- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
    versioningScheme: 'on'
- task: PublishBuildArtifacts@1
  displayName: 'push to pipeline'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Csharp-New-Zip'
    publishLocation: 'Container'