name: C Sharp Dev Build and Package pipeline

variables:
  dir: 'cd root-path/main'
  file: 'csharp.zip'

trigger: 
-  env1
-  env2

stages:
- stage: Build and Test
  jobs:
    - job: Set up Runtime
      pool: 
      steps:
        -  task:

        -  task:

        -  script: ./a.out
    
    - job: Check
      pool: 
      steps:
      -  script: ls

- stage: Deploy
  jobs:
  - job: Deploy to Lambda
    steps:
      - task: LambdaNETCoreDeploy@1
        inputs:
          awsCredentials: 'AWS-GP-Csharp-Deploy'
          regionName: 'ap-south-1'
          command: 'deployFunction'
          packageOnly: false
          functionName: 'DemoCsharpDeploy'
          codeLocation: