name: CSharp Build $(Date:yyyyMMdd) $(Rev:r)

trigger:
- dev

pool:
  vmImage: windows-latest

stages:
-  stage: Build
   displayName: Build Stage
   jobs:
   -  job: 'Build_Job'
      steps:
      - task: UseDotNet@2
        displayName: 'Installing .Net6'
        inputs:
          version: '6.x'
      - task: DotNetCoreCLI@2
        displayName: 'Build'
        inputs:
          command: 'build'
      - task: DotNetCoreCLI@2
        displayName: 'Unit Test'
        inputs:
          command: 'test'
      - task: DotNetCoreCLI@2
        displayName: 'Publish'
        inputs:
          command: 'publish'
          projects: '**/*.csproj'
          publishWebProjects: false
          arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
          zipAfterPublish: true
          versioningScheme: 'on'
      - task: PublishBuildArtifacts@1
        displayName: 'push to pipeline'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'Csharp-New-Zip'
          publishLocation: 'Container'

-  stage: Deploy
   displayName: Download and Deploy
   jobs:
   -  job: 'Deploy_Job'
      steps:
      - task: DownloadBuildArtifacts@0
        displayName: Download the Zip
        inputs:
          buildType: current
          downloadType: single
          artifactName: 'Csharp-New-Zip'
          downloadPath: $(System.ArtifactsDirectory)
      - task: S3Upload@1
        displayName: Upload to S3
        inputs:
          awsCredentials: 'AWS-GP-Csharp-Deploy'
          regionName: 'ap-south-1'
          bucketName: 'azure-new-csharp'
          sourceFolder: $(System.ArtifactsDirectory)
          globExpressions: '**'
          createBucket: true



# - task: PublishPipelineArtifact@1
#   displayName: 'Pushing out'
#   inputs:
#    targetPath: '$(Build.ArtifactStagingDirectory)' 
#    artifactName: 'CSharp-Build'

#- task: DotNetCoreCLI@2
#  displayName: 'packaging'
#  inputs:
#    command: 'pack'
#    packagesToPack: '**/*.csproj'
#    configurationToPack: $(BuildConfiguration)
#    outputDir: $(Build.ArtifactStagingDirectory)
#    versioningScheme: 'off'

# -  task: ArchiveFiles@2
#    displayName: 'Archive files'
#   inputs:
#      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/'
#      includeRootFolder: false
#      archiveType: zip
#      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
#      replaceExistingArchive: false
      
# -  task: PublishBuildArtifacts@1
#    inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
#     ArtifactName: 'Csharp-Zip'
#     publishLocation: 'Container'